dist: xenial
language: python
python:
  - "3.7"
env:
  - FLASK=1.0.2
  - FLASK=1.1.1
install:
  - pip install pytest==5.0.1 pytest-cov==2.7.1 codecov
  - pip install -r requirements.txt
  - pip install flask==$FLASK
script:
  - pytest --cov=flask_hintful
after_success:
  - codecov
